# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CILX5jXqlNltyuNPwXeTAHmfCIhmOkaL
"""

import json
import csv

from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/MyDrive/Colab Notebooks/arxiv-metadata-oai-snapshot.json') as f:
    df = f.read()

!pip install openai
import openai
openai.api_key = "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"

import time

json_objects = df.split('\n')
json_array = '['
input_file = '/content/drive/MyDrive/Colab Notebooks/arxiv-metadata-oai-snapshot.json'

output_file = "abs2.csv"
with open(input_file, "r") as f_in, open(output_file, "w", newline="") as f_out:
  writer = csv.writer(f_out)

  # iterate over each JSON object in the input file
  i = 0
  iteration = 0
  start_time = time.time()
  for line in f_in:
      if(i==10000): break
      i=i+1
      # parse the JSON object and extract the required fields
      data = json.loads(line.strip())
      title = data["title"]
      authors = data["authors"]
      abstract_human = data["abstract"]
      prompt = "Write formal abstract of the research paper with title =" + title +",Authors = " + authors+ ". Only write abstract assuming you are the author"
      response = openai.Completion.create(
          engine="text-davinci-003",
          prompt=prompt,
          stop=None,
          n=1,
          max_tokens = 1000
      )
      abstract_ai = response.choices[0].text
      

      # write the fields as a row to the CSV file
      writer.writerow([title, authors, abstract_human, abstract_ai])
      i = i+1
      iteration = iteration+1
      if iteration >= 59:
        # Calculate the elapsed time
        elapsed_time = time.time() - start_time

        # Check if the elapsed time is less than the time limit
        if elapsed_time < 62:
            # Calculate the remaining time to wait
            wait_time = 62 - elapsed_time

            # Print the remaining time to wait
            print("Waiting for", wait_time, "seconds...")

            # Sleep for the remaining time
            time.sleep(wait_time)

            # Reset the iteration counter and start time
            iteration = 0
            start_time = time.time()
        else:
            # Reset the iteration counter and start time
            iteration = 0
            start_time = time.time()
      else:
        # Sleep for a short duration (e.g., 1 second) before the next iteration
        time.sleep(0)

import pandas as pd

df = pd.read_csv("/content/output.csv", header = None)

df.head()

df.shape

print(df[3][20])

headers = ['id', 'name', 'age', 'gender']